{% set name = "statsmodels" %}
{% set version = "0.13.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/statsmodels-{{ version }}.tar.gz
  sha256: 593526acae1c0fda0ea6c48439f67c3943094c542fe769f8b90fe9e6c6cc4871

build:
  number: 0
  skip: true  # [py<37] 
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
    - setuptools
    - setuptools_scm >=7.0,<8
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3
    - packaging >=21.3
    - pandas >=0.25
    - patsy >=0.5.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Statistical computations and models for use with SciPy
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.
  doc_source_url: https://github.com/statsmodels/statsmodels/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
