{% set version = "0.11.0" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 0a8ee8fc091d9ef1db68f01e6e0079acc0f41671dfbac463131939ca573f8c71

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: True  # [py2k]  

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - scipy >=1.0
    - pandas >=0.21
    - patsy >=0.5.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0
    - pandas >=0.21
    - patsy >=0.5.1

test:
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: INSTALL.txt
  license_family: BSD
  summary: 'Statistical computations and models for use with SciPy'
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.
  doc_source_url: https://github.com/statsmodels/statsmodels/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
