{% set version = "0.10.1" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: 320659a80f916c2edf9dfbe83512d9004bb562b72eedb7d9374562038697fa10

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"                # [not win]
  script: python setup.py install --single-version-externally-managed --record record.txt  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - scipy >=0.14
    - pandas >=0.14
    - patsy >=0.4.0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.14
    - pandas >=0.14
    - patsy >=0.4.0

test:
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD 3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: 'Statistical computations and models for use with SciPy'
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.
  doc_source_url: https://github.com/statsmodels/statsmodels/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
