{% set version = "0.13.0" %}

package:
  name: statsmodels
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/statsmodels/statsmodels-{{ version }}.tar.gz
  sha256: f2efc02011b7240a9e851acd76ab81150a07d35c97021cb0517887539a328f8a

build:
  number: 0
  skip: true  # [py<37] 
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"                # [not win]
    - "rm -f ${PREFIX}/LICENSE.txt"                                                    # [not win]
    - "rm -f ${PREFIX}/setup.cfg"                                                      # [not win]
    - python setup.py install --single-version-externally-managed --record record.txt  # [win]
    - "del /f /q %PREFIX%\\LICENSE.txt"                                                 # [win]
    - "del /f /q %PREFIX%\\setup.cfg"                                                   # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.29.22
    # Do not add any constraint on numpy here to use global pinning from cbc.yml on aggregate repo
    - numpy
    - scipy >=1.3
    - setuptools
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.3
    - pandas >=1.0
    - patsy >=0.5.2

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - statsmodels

about:
  home: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: INSTALL.txt
  license_family: BSD
  summary: 'Statistical computations and models for use with SciPy'
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.
  doc_source_url: https://github.com/statsmodels/statsmodels/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
