{% set name = "statsmodels" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6875c7d689e966d948f15eb816ab5616f4928706b180cf470fd5907ab6f647a4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython 0.29.32
    - numpy {{ numpy }}
    - pip
    - scipy
    - setuptools
    - setuptools_scm 7.0.4
    - toml
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - packaging >=21.3
    - pandas >=1.0
    - patsy >=0.5.2
    - scipy >=1.4,!=1.9.2

test:
  imports:
    - statsmodels
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.statsmodels.org
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Statistical computations and models for use with SciPy
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
