{% set name = "statsmodels" %}
{% set version = "0.14.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: de260e58cccfd2ceddf835b55a357233d6ca853a1aa4f90f7553a52cc71c6ddf

build:
  skip: true  # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython >=3.0.10,<4
    - numpy {{ numpy }}
    - pip
    - scipy >=1.13,<2
    - setuptools >=69.0.2
    - setuptools_scm >=8.0,<9
  run:
    - python
    - numpy  >=1.22.3,<3
    - packaging >=21.3
    - pandas >=1.4,!=2.1.0
    - patsy >=0.5.6
    - scipy >=1.8,!=1.9.2

test:
  imports:
    - statsmodels
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.statsmodels.org
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org/stable/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Statistical computations and models for use with SciPy
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
