{% set name = "statsmodels" %}
{% set version = "0.15.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d257fe58d0772bc46a557880ca78e2a8e07fec7bfd9d11074aef8e33e1aecbc

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=3.0.13,<4
    - numpy >=2.0.0,<3
    - scipy >=1.13,<2
    - setuptools_scm >=9.2.0,<10
    - toml >=0.10.2
    - meson-python
    # meson-python require ninja-base >=1.8.2 in host section
    # https://github.com/AnacondaRecipes/meson-python-feedstock/blob/4f6666a76460307daccaacf896184ed763ba0919/recipe/meta.yaml#L31
    - ninja-base >=1.8.2
  run:
    - python
    - numpy >=1.23.5,<3
    - scipy >=1.8,!=1.9.2
    - pandas >=1.4,!=2.1.0
    - patsy >=0.5.6
    - packaging >=21.3
    - formulaic >=1.1.0
    - ninja-base >=1.8.2
  run_constrained:
    - polars >=1.0.0

# E fixture 'reset_randomstate' not found
# E Failed: DID NOT WARN. No warnings of type (<class 'statsmodels.tools.sm_exceptions.HessianInversionWarning'>,) were emitted.
# > raise ValueError("Cannot use capturing groups in re.Scanner")

{% set deselect_tests = "--deselect=statsmodels/base/tests/test_generic_methods.py::TestGenericGLM::test_zero_collinear" %}
{% set deselect_tests = deselect_tests + " --deselect=statsmodels/base/tests/test_generic_methods.py::TestGenericGLMPoissonOffset::test_zero_collinear" %}
{% set deselect_tests = deselect_tests + " --deselect=statsmodels/base/tests/test_optimize.py::test_full_output_false" %}
{% set deselect_tests = deselect_tests + " --deselect=statsmodels/base/tests/test_optimize.py::test_full_output" %}
{% set ignore_tests = " --ignore=statsmodels/base/tests/test_generic_methods.py" %}
{% set ignore_tests = ignore_tests + " --ignore=statsmodels/base/tests/test_shrink_pickle.py" %}

test:
  source_files:
    - statsmodels/base/tests
  imports:
    - statsmodels
  requires:
    - pip
    - pytest >=8.4.1,<10
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs {{ deselect_tests }} {{ ignore_tests }}

about:
  home: https://www.statsmodels.org
  dev_url: https://github.com/statsmodels/statsmodels
  doc_url: https://www.statsmodels.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  summary: Statistical computations and models for use with SciPy
  description: |
    Statsmodels is a Python module that allows users to explore data, estimate
    statistical models, and perform statistical tests. An extensive list of
    descriptive statistics, statistical tests, plotting functions, and result
    statistics are available for different types of data and each estimator.
    Researchers across fields may find that statsmodels fully meets their
    needs for statistical computing and data analysis in Python.

extra:
  recipe-maintainers:
    - tomaugspurger
    - croth1
    - ocefpaf
  skip-lints:
    - host_section_needs_exact_pinnings
