travis:
  secure:
    BINSTAR_TOKEN: F1vZV+UxcaoJZCQWUahL5riegugwqIJrmwUtAMDP5HIeqL1QhBjvSW0idrkEbdQozVvnlwAvGvjKFjSXkmk3H+4goQH8N5Kb2rQUcFh+AcnppBKw4LZADIRtABrJ6OFlE9l+MmXrGEvLzxmDNF9UUtUTuFYKilhMTxmQZFSwNus2a0AMmeff23vsY9CnK0aM2fyBVCFflAeMQX0CaI4j6Kh95CRQwum37SLx31PJSGrU9Sxo/ju7rMmefvtv3vZF51smabsc79Vm/yOgDBUtr2nmpJ8BDXfZwlyROPN4wcmJK3fjxR0SXUHgLw7oXB7DUu+IKo7guODAFPEgjihtznFO1fQ6DIDEdD/XeI4iW8cFaNBldIegYlik+jfHbz5M99k6Wn8KQ80nzcnmb0q9CLsv53ks9+YXW4AG4YjUSHzjI6qP+hdY7pPynwhgoZyJ91qCy6XGpLHImSaCi+CVPLNX3r1XxU8GGOQWCbLFvsT0KM1ElTRw12CArygL31oUsQO9rlYhtywf1Xu34H5j2Rlxuvbc00juWbKU3IeueLxtJAIQvdDqNEg9WJbdcrmxjHsko47ZHdTZxWX9399P60gcIKr64qEcZ1/KlsOA2Cd1D4lN0vlguYsLliJj2NWw/ubdRb/K7YZTnDjdKhssK6VfDXhcs8zSn2puLA7qTys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
